### ISSUE TITLE
Has this project been dropped?

### ISSUE THREAD

**Issue by Casuallynoted** [vinxce/RMMV-MMO-webkit#1]
Hello!

I wasn't quite sure where to ask this so I figured I should put it here. xD Has this project been dropped? It seems very promising, and I found a list online of some of the features you were looking to add. It would definitely be a fantastic asset for RPG Maker MV devs. :)

**Comment by SirMcPotato** [comment]
Hi @Casuallynoted!

This project haven't really been dropped, but just put aside for a few moment, because there's a lot of things to rethink in order to allow a true and smooth multiplayer support!
One of the biggest challenge in this project is to build from scratch a brand-new online and in-browser game editor using maybe React or Angular technologies. Another challenge is to properly set up an optimised server/client communication protocol, and I need a bit more experience in this ^^"

This kind of remodeling involve to put a lot of time in it, and at the moment I'm lacking of time du to my challenging full-time job.
Anyway, I eventually plan to come back working on it soon, but there's many point I need to clarify before that.

Stay tuned!

Edit : Updating README.md, thanks to you ;)
